services:
  aadhaar-api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: aadhaar-api
    ports:
      - "8000:8000"
    env_file:
      - .env
    environment:
      - DETAIL_MODEL_PATH=${DETAIL_MODEL_PATH:-yolo-aadhaar-details-v01.pt}
      - REC_MODEL_NAME=${REC_MODEL_NAME:-PP-OCRv5_mobile_rec}
    volumes:
      - ./:/app
    restart: unless-stopped
